/*
 Copyright © 1995, 2021, Oracle and/or its affiliates. All rights reserved.

 For information, please see the following link:
 https://www.oracle.com/legal/copyright.html

 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 odc.js v1.0.7
 Created: 2021-07-28T20:10:30+0000
*/
(function(){function l(v,q){var u={major:1,minor:0,inc:7},h=this,C=!1,B=2E3,x=location.protocol,R="sizzle",O=null,P=!1,E=!1,K=!1,k={};this.getTagId=function(){return"oracledocs"};this.inHead=function(){return E};this.applyStyleSheet=function(a,b){try{var c=q.getElementsByTagName("head")[0],e=q.createElement("style");e.type="text/css";e.id=b;e.styleSheet?e.styleSheet.cssText=a:e.appendChild(q.createTextNode(a));c.appendChild(e)}catch(f){ORA.Debug.error("applyStyleSheet:  Failed to failed to apply stylesheet",
"004",f)}};this.removeStyleSheet=function(a){try{var b=q.getElementById(a);"undefined"!==typeof b&&null!==b&&b.parentNode.removeChild(b)}catch(c){ORA.Debug.debug("removeStyleSheet:  Failed to remove stylesheet")}};this.getSelector=function(){if("sizzle"===R){if("undefined"!==typeof Sizzle&&ORA.hasVal(Sizzle))return Sizzle;if("undefined"!==typeof ORA.Sizzle)return ORA.Sizzle}else{if(null!==O)return O;ORA.Debug.error("getSelector:  No Selector found","003")}return!1};this.setCustomSelector=function(a,
b){R=a;O=b};this.hasVal=function(a){return null!==a&&"undefined"!==typeof a};var X=function(a,b,c){a=h.hasVal(a)&&"shift"!==b&&!E;b=h.hasVal(b);c=h.hasVal(c);return a&&b&&c},Y=function(a,b,c){var e="hideAndShow:  ";e=E?e+"tag inHead":e+"tag not inHead";e=c?e+", showing":e+", hiding";e=a&&a.nodeName?e+(", "+a.nodeName):e+", unnamed elem";return e+('"  with type "'+b+' "')},Z=function(a,b,c){E?a("body{ display: none !important}"):(b.style.display="",c&&(b.style.display="none"),b===q.body||c||(q.body.style.display=
""))},aa=function(a,b,c){E?a("body{ visibility: hidden !important}"):(b.style.visibility="visible",c||(b.style.visibility="hidden"),b.style.hidden=!c,b===q.body||c||(q.body.style.visibility="visible",q.body.style.hidden=!1))},ba=function(a,b,c){c?(a=q.getElementById("ora_shiftStyle"))&&a.parentNode.removeChild(a):(a=q.getElementsByTagName("head")[0],b=q.createElement("style"),b.type="text/css",b.id="ora_shiftStyle",b.styleSheet?b.styleSheet.cssText="body{position:absolute !important; left: -1000% !important; visibility: hidden}":
b.appendChild(q.createTextNode("body{position:absolute !important; left: -1000% !important;}")),a.appendChild(b))},ca=function(a,b,c,e){b=q.getElementById("ora_overlay");var f=q.getElementById("ora_overlayStyle");a=e;h.hasVal(e)&&(a="#ffffff");c&&b?(b.parentNode.removeChild(b),f&&f.parentNode.removeChild(f)):c||b||(E&&h.Debug.error("hideAndShow: Warning! tag detected in head, overlay mode may error out or cause flickering","007"),f||(c=q.createElement("style"),c.setAttribute("type","text/css"),c.setAttribute("id",
"ora_overlayStyle"),a="#ora_overlay{position:absolute;width:100%;height:100%;top:0px;right:0px;bottom:0px;left:0px;background-color:"+(a+";z-index:2147483646}"),c.styleSheet?c.styleSheet.cssText=a:c.appendChild(q.createTextNode(a)),q.getElementsByTagName("head")[0].appendChild(c)),h.hasVal(e)?b=q.createElement("div"):(b=q.createElement("iframe"),b.frameBorder=0),b.id="ora_overlay",q.getElementsByTagName("body")[0].appendChild(b))};this.hideAndShow=function(a,b,c){try{if(X(a,b,c)){h.Debug.debug(Y(a,
b,c));var e=function(f){c?h.removeStyleSheet("o_style"):h.applyStyleSheet(f,"o_style")};switch(b){case "display":Z(e,a,c);break;case "visibility":aa(e,a,c);break;case "shift":case "supershift":ba(e,a,c);break;case "overlay":ca(e,a,c);break;case "none":ORA.Debug.trace("LOADER: type: none");break;default:h.Debug.debug("hideAndShow did not contain a matching type, so not hiding/showing")}e={};e.displayType=b;e.display=c;h.fireEvent(new ORA.Event(ORA.Event.HIDESHOW,ORA.Event.STATUS_SUCCESS,a,e))}else h.Debug.error("hideAndShow param list incomplete",
"006")}catch(f){h.Debug.error("Failure in hide/show functionality.  Verify valid HTML syntax","008",f)}};E=function(){try{var a=q.getElementsByTagName("script");return"HEAD"===a[a.length-1].parentNode.nodeName}catch(b){return WT.Debug.error("inHead: Failed to detect if in head, assuming inHead","001",b),!0}}();var D=function(){P||(P=!0,ORA.fireEvent(new ORA.Event(ORA.Event.DOM_READY,ORA.Event.STATUS_SUCCESS),!0))},L=function(){K||(K=!0,ORA.fireEvent(new ORA.Event(ORA.Event.DOM_ONLOAD,ORA.Event.STATUS_SUCCESS),
!0))},S=function(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var e=[];e[0]=b[c].substring(0,b[c].indexOf("\x3d"));for(e[1]=b[c].substring(b[c].indexOf("\x3d")+1);" "===e[0].charAt(0);)e[0]=e[0].substring(1,e[0].length);if(e[0]===a)return e[1]}return null},T=function(a){for(var b=document.getElementsByTagName("meta"),c=0;c<b.length;c++)if(b[c].name===a)return b[c].content;return null};this.execute=function(a){Array.prototype.slice.call(arguments,1);fireEventName(ORA.Event.LOADER_PRE_EXECUTE,
a);fireEventName(ORA.Event.LOADER_EXECUTE,a)};this.loaderConversionTimeoutDefault=function(){return B};this.setLoaderConversionTimeoutDefault=function(a){B=a};this.reset=function(){for(var a in k)k.hasOwnProperty(a)&&k[a].reset();fireEventName(ORA.Event.LOADER_RESET,null)};this.pollForCondition=function(a,b,c){var e=200,f=function(g,d,n,m,t){window.setTimeout(function(){e--;g()?(h.Debug.trace("pollForCondition success result\x3d"+g(),"LOADER"),h.Debug.superfine("pollForCondition success condition\x3d"+
g.toString(),"LOADER"),d&&(d(),h.Debug.trace("pollForCondition running callback","LOADER"),h.Debug.superfine("pollForCondition callback\x3d"+d.toString(),"LOADER"))):0<e?(h.Debug.trace("LOADER:  pollForCondition timeoutCount\x3d"+e),f(g,d,n,e)):(h.Debug.error("pollForCondition Fail on "+g.toString(),"009"),n&&(n(),h.Debug.superfine("pollForCondition callbackFailure\x3d"+n.toString(),"LOADER")))},t)};f(a,b,c,e,5)};this.paramsMerge=function(a,b,c){var e={};if(ORA.hasVal(a))for(var f in a)a.hasOwnProperty(f)&&
(e[f]=a[f]);for(var g in b)ORA.hasVal(b[g])&&b.hasOwnProperty(g)&&(ORA.hasVal(c)&&ORA.hasVal(c[g])?e[g]=c[g]:e[g]=b[g]);return e};this.downloadLib=function(a,b,c,e,f,g){g&&(h.Debug.info("LOADER:  Start download: "+x+g+" \x26 attach to "+a+", async\x3d"+f),window.setTimeout(function(){var d=q.getElementsByTagName(a)[0],n=q.createElement("script");n.type="text/javascript";n.src=x+g;n.setAttribute("async",f);n.setAttribute("defer",f);n.oraHasRun=!1;var m=function(){!1===this.oraHasRun?(b(),this.oraHasRun=
!0,h.Debug.info("Completed download: "+x+g+", callback running oraHasRun\x3d"+this.oraHasRun,"LOADER"),h.Debug.superfine("downloadLib: successCallback\x3d"+b.toString(),"LOADER")):h.Debug.trace("downloadLib: not running successCallback, since oraHasRun\x3d"+this.oraHasRun,"LOADER")};b&&(n.onload=m,n.onreadystatechange=m);n.onerror=function(){h.Debug.error("FAILED download: "+x+g+" \x26 attach to "+a+", async\x3d"+f,"010");c&&(c(),h.Debug.superfine("failCallback: "+c.toString(),"LOADER"))};"undefined"!==
typeof d?d.appendChild(n):h.Debug.info("LOADER:  Dom element: "+a+" is not found so not Downloading")},e))};this.downloadLibs=function(a,b,c,e,f){if("undefined"===typeof f)h.Debug.info("LOADER:  downloadLibs srcs is empty");else{var g={},d=function(m){return function(){g[m]="complete";h.Debug.trace("LOADER:  downloadLibs is complete src:"+m+" \x3d "+f[m])}},n;for(n in f)f.hasOwnProperty(n)&&(g[n]="waiting",h.Debug.trace("LOADER:  downloadLibs is waiting on src:"+n+" \x3d "+f[n]),h.downloadLib(a,d(n),
null,c,e,f[n]));h.pollForCondition(function(){for(var m in g)if(g.hasOwnProperty(m)&&"complete"!==g[m])return!1;return!0},function(){h.Debug.debug("LOADER:  downloadLibs completed on all downloads");b()})}};this.parseQueryString=function(a){var b=a;h.hasVal(a)&&h.hasVal(a.location)&&h.hasVal(a.location.search)||(b=document);a=function(c){var e=c.split("\x26"),f={};null!==e&&0===e.length&&(e=c.split(";"));if(null===e)return f;c=0;e&&(c=e.length-1);for(var g=0;g<=c;g++){var d=e[g].split("\x3d");d[0]=
unescape(d[0]);d[1]=unescape(d[1]);d[0]=d[0].replace(/\+/g," ");d[1]=d[1].replace(/\+/g," ");d[1]=d[1].replace(/<.*\?>/g,"");f[d[0]]=d[1]}return f};return b.location.search?(b=b.location.search.substring(1,b.location.search.length),a(b)):b.location.href?(b=b.location.href.split("?"),2===b.length?a(b[1]):null):null};this.abortModuleHelper=function(a,b){ORA.fireEvent(new ORA.Event(a+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS));ORA.setExecuteState(a,ORA.Event.LOADER_MODULE_ABORT);ORA.Debug.error("Aborting product: "+
a,"011");ORA.Debug.error("LOADER Error","011",b)};this.Event=function(a,b,c,e){a&&(a=a.toLowerCase());this.name=a;this.handler=null;this.state=ORA.Event.STATUS_UNKNOWN;b&&(this.state=b);this.target=c;this.params={};e&&(this.params=e)};this.fireEventName=function(a,b){ORA.fireEvent(new ORA.Event(a,ORA.Event.STATUS_SUCCESS,null,b),null,null,!0)};this.EventEngineClass=function(){var a={},b={},c=function(g,d,n,m){C&&!m&&h.Debug.error("fireEvent: Loader global abort, Aborted due to prior error","012",
null,"LOADER");d.handler=g;d.params.eventID=(new Date).getTime();m="not set";n&&(m=n);h.Debug.trace("fireEvent: [name: "+d.name+"], state:"+d.state+"async["+m+"]","LOADER");h.Debug.superfine("function:"+d.handler.toString()+"]","LOADER");n?window.setTimeout(function(t,w){return function(){t(w)}}(g,d),0):d.handler(d);return 1},e=function(g,d,n,m,t){for(var w=0;w<b[g][t].length;w++)if(h.hasVal(b[g][t][w])&&b[g][t][w].toString()===m.toString()&&!0!==d){n=!0;break}n||(b[g][t].push(m),d="addEventHandler success handler"+
b[g][t].length,d+=" for "+g+"\nhandler\x3d"+m.toString(),h.Debug.superfine(d,"LOADER"));return n};a.addEventHandler=function(g,d,n,m){var t=g;g=0;var w=!1;if(!t||!d&&!n)return h.Debug.debug("events: Can not add event handler, missing name or listeners. ","LOADER"),-1;var z=t=t.toLowerCase();b[z]||(b[z]={});b[z].success||(b[z].success=[]);b[z].fault||(b[z].fault=[]);d&&(w=e(t,m,!1,d,"success"));w||(g=1);n&&(w=e(t,m,!1,n,"fault"));w||(g+=1);m=t;if(b[m].queue&&0!==b[m].queue.length)for(t=b[m].queue.length-
1;0<=t;t--)w=b[m].queue[t],d&&"success"===w.event.state?c(d,w.event,w.async,w.override):n&&"fault"===w.event.state&&c(n,w.event,w.async,w.override),b[m].queue.splice(t,1);return g};var f=function(g,d,n){for(var m=0;m<b[g][n].length;m++)if(h.hasVal(b[g][n][m])&&b[g][n][m].toString()===d.toString())return b[g][n].splice(m,1),1;return 0};a.removeEventHandler=function(g,d,n){if(!g)return h.Debug.trace("LOADER removeEventHandler:  events: Can not remove event handler, missing event name."),-1;g=g.toLowerCase();
if(!b[g])return 0;if(!d&&!n)return delete b[g],0;var m=0;d&&(m+=f(g,d,"success"));n&&(m+=f(g,n,"fault"));return m};a.fireEvent=function(g,d,n,m){if(C&&!n)return h.Debug.error("fireEvent: Loader global abort, Aborted due to prior error","012",null,"LOADER"),g.name?h.Debug.error("fireEvent(event\x3d"+g.name+"): g_loaderAborted due to prior error","012",null,"LOADER"):h.Debug.error("fireEvent: Aborted due to prior error, check error message for details.","012"),-1;var t=g.name,w=g.state;var z=!!b[t],
F=!(!z||!b[t][w]),M=!(!z||!b[t].queue);F&&0!==b[t][w].length||!m?z?F?m=1:(h.Debug.trace("fireEvent: [name:"+t+", state:"+w+"] no event handler was found","LOADER"),m=-1):(h.Debug.trace("fireEvent: [name: "+t+"], no registered event was found","LOADER"),m=-1):(h.Debug.trace("fireEvent: [name: "+t+"], no registered event was found, enqueueing","LOADER"),z||(b[t]={}),M||(b[t].queue=[]),b[t].queue.push({event:g,async:d,override:n}),m=0);if(0>=m)return m;m=b[t][w];for(F=z=0;F<m.length;F++)if(m[F])try{c(m[F],
g,d,n),z++}catch(da){M="Unhandled Event Exception, [name: "+t+", state: "+w+", function: ",M+=g.handler.toString()+"]",h.Debug.error(M,"013",da)}return z};a.getEventHandlers=function(){return b};a.length=function(){var g=0,d;for(d in b)b.hasOwnProperty(d)&&g++;return g};a.addFireOnce=function(g,d,n){var m=function(){d();a.removeEventHandler(g,m,n)};a.addEventHandler(g,m,n)};a.clearAllEventHandlers=function(){b={}};return a};var I=new this.EventEngineClass;this.addEventHandler=I.addEventHandler;this.removeEventHandler=
I.removeEventHandler;this.fireEvent=I.fireEvent;this.addFireOnce=I.addFireOnce;this.clearAllEventHandlers=I.clearAllEventHandlers;this.Event.PREINIT="preinit";this.Event.INIT="init";this.Event.PRELOAD="preload";this.Event.LOAD="load";this.Event.POSTLOAD="postload";this.Event.LOADER_ABORT="loader_abort";this.Event.LOADER_MODULE_ABORT="loader_module_abort";this.Event.DEBUGGER_CLEAR_COOKIES="debugger_clear_cookies";this.Event.DEBUGGER_DUMP_PARAMS="debugger_dump_params";this.Event.DEBUG_ERROR_OUT="debug_error_out";
this.Event.DOM_READY="dom_ready";this.Event.DOM_ONLOAD="dom_onload";this.Event.TIMER_EXPIRE="timer_expire";this.Event.TIMER_CLEAR="timer_clear";this.Event.STATUS_SUCCESS="success";this.Event.STATUS_FAULT="fault";this.Event.STATUS_UNKNOWN="unknown";this.Event.PAGEVIEW="pageview";this.Event.CONVERSION="conversion";this.Event.DEBUGGER_CHECK_MODE="debugger_check_mode";this.Event.SCRIPT_LOAD_COMPLETE="script_load_complete";this.Event.HIDESHOW="hide_show";this.Event.SET_CLIENT_ID="set_client_id";this.Event.CLEAR_CLIENT_ID=
"clear_client_id";this._Debug=function(){var a=-1;this._shutdown=!1;var b=[],c=this,e=function(f,g,d){d&&(g=d+":  "+g);if(!(a<f)&&"undefined"!==typeof console&&console){d=!0;switch(f){case 0:console.error&&(console.error(g),d=!1);break;case 1:console.warn&&(console.warn(g),d=!1);break;case 2:console.info&&(console.info(g),d=!1);break;case 3:case 4:case 5:console.log&&(console.log(g),d=!1)}!0===d&&console.log&&console.log(g)}};c.superfine=function(f,g){e(5,f,g)};c.trace=function(f,g){e(4,f,g)};c.debug=
function(f,g){e(3,f,g)};c.info=function(f,g){e(2,f,g)};c.error=function(f,g,d,n){var m="";d&&("string"===typeof d?m="\n"+d:d.toString?(m=d.toString(),d.stack&&(m+=", [stack]: "+d.stack)):m=d.message?d.name?d.fileName?"\n"+d.message+" ["+d.name+"]\n ("+d.fileName+":"+d.lineNumber+")\n"+d.stack:"\n"+d.message+" ["+d.name+"]":d.fileName?"\n"+d.message+"\n ("+d.fileName+":"+d.lineNumber+")\n"+d.stack:"\n"+d.message:d.name?d.fileName?"\n ["+d.name+"]\n ("+d.fileName+":"+d.lineNumber+")\n"+d.stack:"\n ["+
d.name+"]":d.fileName?"\n\n ("+d.fileName+":"+d.lineNumber+")\n"+d.stack:"\n");e(0,(g?g+": ":"")+f+m,n);ORA.fireEvent(new ORA.Event(ORA.Event.DEBUG_ERROR_OUT,ORA.Event.STATUS_SUCCESS,d))};c.dir=function(f,g,d){g&&e(2,g,d);console&&"function"===typeof console.dir?console.dir(f):c.dirStr(f)};c.dirStr=function(f,g){var d=f||{},n=g||"",m;for(m in d)d.hasOwnProperty(m)&&"function"!==typeof d[m]&&c.debug("\t"+m+" : "+d[m],n)};c.setDebugLevel=function(f){a=f};c.getDebugLevel=function(){return a};c.dumpParams=
function(){var f=c.getConfigParams(),g;for(g in f)f.hasOwnProperty(g)&&"object"===typeof f[g]&&c.dir(f[g],"Config parameters",g);return f};c.getConfigParams=function(){var f={};f.loader={version:u,versionStr:[u.major,u.minor,u.inc].join(".")};return f};c.checkMode=function(f){ORA.fireEvent(new ORA.Event(ORA.Event.DEBUGGER_CHECK_MODE,ORA.Event.STATUS_SUCCESS,{resetFlag:f}))};c.getHistory=function(){return b}};var U=function(a,b){this._name=a;this._state=b;this._met=!1},y=function(a,b,c){var e=this,
f={},g=[];this.prodId=a;this.plugin=new b;this.executeState=y.WAITING;this.stopTime=this.startTime=this.timer=null;this.configName="default";"undefined"!==typeof c&&(this.configName=c);this.putDependency=function(d){f[d._name]=d};this.reset=function(){e.executeState=y.WAITING;f={};g=[]};this.clearDependencies=function(){f={}};this.getDependency=function(d){for(var n in f)if(f.hasOwnProperty(n)&&f[n]._name===d)return f[n];return null};this.getDependents=function(){0===g.length&&(g=ORA.getDependents(e.prodId));
return g};this.updateDependents=function(){g=ORA.getDependents(e.prodId)};this.getExecuteState=function(){return this.executeState};this.hasMetDeps=function(){for(var d in f)if(f.hasOwnProperty(d)&&""!==d&&!0!==f[d]._met)if(k[d].getExecuteState()===f[d]._state)f[d]._met=!0;else return!1;return!0};this.updateDependencyState=function(d,n){var m=e.getDependency(d);null!==m&&m._state===n&&(m._met=!0)};this._startTimer=function(d){this.timer?h.Debug.info("LOADER:  "+this.prodId+" timer already started, using current timer."):
(h.Debug.debug("LOADER:  starting timer for "+e.prodId),this.timer=window.setTimeout(function(){h.Debug.error("LOADER:  "+e.prodId+"module timer expired calling Abort","015");h.fireEvent(new ORA.Event(e.prodId+"_"+ORA.Event.TIMER_EXPIRE,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(e.prodId+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},d),this.startTime=new Date,h.Debug.info("LOADER:  "+this.prodId+" timer started ["+this.startTime+"]."))};this._clearTimer=function(){this.stopTime=
new Date;this.timer&&(clearTimeout(this.timer),this.timer=null);h.Debug.info("LOADER:  "+this.prodId+" timer cleared ["+this.stopTime+"]")};this.tryExecPostload=function(){var d=e.getExecuteState()===y.READY,n=e.hasMetDeps(),m=void 0!==e.plugin[ORA.Event.POSTLOAD];if(n&&d&&m)return h.Debug.debug("setExecuteState:  "+e.prodId+" has met all dependencies \x26\x26 ready, running postload"),e.plugin[ORA.Event.POSTLOAD](),!0;if(n&&d)return ORA.Debug.superfine(e.prodId+", has no postLoad section"),!0;ORA.Debug.superfine(e.prodId+
", did not meet postload exec conditionals");return!1}};y.WAITING="waiting";y.DOWNLOADING="downloading";y.READY="ready";y.RUNNING="running";y.ABORTED="aborted";this.registerPlugin=function(a,b){k[a.ProductName]=new y(a.ProductName,a,b);k[a.ProductName].executeState=y.WAITING;ORA.hasVal(a.prototype.abort)&&ORA.addEventHandler(a.ProductName+"_"+ORA.Event.LOADER_MODULE_ABORT,a.prototype.abort);if(ORA.hasVal(a.prototype.oraConfigObj)&&ORA.hasVal(a.prototype.oraConfigObj.s_dependencies))for(var c=a.prototype.oraConfigObj.s_dependencies.split(","),
e=0;e<c.length;e++){var f=c[e].split(":");k[a.ProductName].putDependency(new U(f[0],f[1]))}for(var g in k)k.hasOwnProperty(g)&&k[g].updateDependents();a.prototype&&a.prototype.oraConfigObj&&a.prototype.oraConfigObj.s_useTrackingPipeline&&!0===a.prototype.oraConfigObj.s_useTrackingPipeline&&(k[a.ProductName].useTrackingPipeline=!0,c=a.prototype.oraConfigObj,ORA.hasVal(c.s_pageTimeout)&&ORA.hasVal(c.s_TrackingPipelineTimeout)?k[a.ProductName].s_TrackingPipelineTimeout=Math.max(c.s_pageTimeout,c.s_TrackingPipelineTimeout):
ORA.hasVal(c.s_pageTimeout)?k[a.ProductName].s_TrackingPipelineTimeout=c.s_pageTimeout:ORA.hasVal(c.s_TrackingPipelineTimeout)&&(k[a.ProductName].s_TrackingPipelineTimeout=c.s_TrackingPipelineTimeout))};this.clearPlugins=function(){k={}};this.hasMetDeps=function(a){return k[a].hasMetDeps()};this.getDependents=function(a){var b=[],c;for(c in k)k.hasOwnProperty(c)&&null!==k[c].getDependency(a)&&b.push(c);return b};this.updateDependencies=function(a,b){if(!a||!k[a])return null;if(!b)return k[a].clearDependencies(),
null;var c=b.split(",");if(!c||0===c.length)return null;k[a].clearDependencies();for(var e=0;e<c.length;e++){var f=c[e].split(":");if(2===f.length)k[a].putDependency(new U(f[0],f[1]));else break}return null};var V=function(a){var b=k[a];if(b.tryExecPostload()){b.executeState="running";a=b.getDependents(a);for(var c in a)a.hasOwnProperty(c)&&V(a[c])}};this.setExecuteState=function(a,b){if(b===ORA.Event.LOADER_MODULE_ABORT)k[a].executeState=y.ABORTED;else if(h.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT){k[a].executeState=
b;h.Debug.trace("setExecuteState:  "+a+" to "+b);var c=k[a].getDependents(),e;for(e in c)c.hasOwnProperty(e)&&k.hasOwnProperty(c[e])&&k[c[e]].updateDependencyState(a,b);V(a)}};this.getExecuteState=function(a){return ORA.hasVal(k[a])?k[a].executeState===y.ABORTED?ORA.Event.LOADER_MODULE_ABORT:k[a].executeState:null};this.isDependency=function(a){for(var b in k)if(k.hasOwnProperty(b)&&null!==k[b].getDependency(a))return h.Debug.trace("isDependency:  "+a+" is dependency of "+b),!0;h.Debug.trace("isDependency:  "+
a+" is not a dependency of any product");return!1};this.getTrackingPipelineProducts=function(){var a=[],b;for(b in k)if(k.hasOwnProperty(b)&&k[b].useTrackingPipeline){var c={};c.name=b;k[b].s_TrackingPipelineTimeout&&(c.timeout=k[b].s_TrackingPipelineTimeout);a.push(c)}return a};this.getContextUrl=function(a,b){return"//c.oracleinfinity.io/acs/account/wh3g12c3gg/js/oracledocs/"+a+"-"+b+".js"};this.getProduct=function(a){for(var b in k)if(k.hasOwnProperty(b)&&a===k[b].prodId)return k[b];return null};
this.isProductEnabled=function(a){a+="Module";return ORA[a]&&ORA[a].prototype.oraConfigObj?void 0===ORA[a].prototype.oraConfigObj.enabled?!0:ORA[a].prototype.oraConfigObj.enabled:!1};this.isReady=function(){return P};this.isLoaded=function(){return K};this.addDOMEvent=function(a,b,c){try{return a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):eval("elm."+b+"\x3dfunc;"),0}catch(e){return-1}};this.removeDOMEvent=function(a,b,c){try{return a.removeEventListener?a.removeEventListener(b,
c,!1):a.detachEvent&&a.detachEvent("on"+b,c),0}catch(e){return-1}};this.getSafeEventName=function(a,b){var c=b.substr(0,2);if(a.addEventListener){if("on"===c)return b.substring(2)}else if(a.attachEvent&&"on"!==c)return"on"+b;return b};var ea=function(){"complete"!==document.readyState&&"undefined"!==typeof document.readyState||D();document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);D()},!1);if(/WebKit|Opera/i.test(navigator.userAgent))var a=
setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(a),D())},10)},fa=function(){"complete"!==document.readyState&&"loading"!==document.readyState||D();document.attachEvent("onreadystatechange",function(){if("complete"===document.readyState||"loading"===document.readyState)document.detachEvent("onreadystatechange",arguments.callee),D()})},ha=function(){try{document.addEventListener&&ea(),document.attachEvent&&fa(),window.addEventListener?window.addEventListener("load",
function(){window.removeEventListener("load",arguments.callee,!1);D()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);D()}),K?L():window.addEventListener?window.addEventListener("load",function(){window.removeEventListener("load",arguments.callee,!1);L()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);L()})}catch(a){D(),L()}};h.Debug=new h._Debug;var G=this.parseQueryString(v);
h.hasVal(G)&&h.hasVal(G["_ora.debug"])&&h.Debug.setDebugLevel(G["_ora.debug"]);var H=function(a){var b={};a=a.split(/[;,]/);for(var c in a)if(a.hasOwnProperty(c)){var e=a[c].split(":");b[e[0]]=e[1]}return b},A=function(){var a=S("_ora.context");var b=S("_ora.config");a=a||b||null;b=T("_ora.context");var c=T("_ora.config");b=b||c||null;c=G&&(G["_ora.context"]||G["_ora.config"]||null);for(var e=document.getElementsByTagName("SCRIPT"),f,g=/_ora\.context=([^&]*)|_ora\.config=([^&]*)/g,d=0;d<e.length&&
!f;d++)e[d].src&&/odc\.js\?/.test(e[d].src)&&(f=g.exec(e[d].src));if(null!==c)return H(c);if("undefined"!==typeof a&&null!==a)return H(a);if("undefined"!==typeof b&&null!==b)return H(b);if(f&&2<f.length)return void 0!==f[2]?H(f[2]):void 0!==f[1]?H(f[1]):H(f[0])}();if("undefined"!==typeof A){h.Debug.info("LOADER:  Found one or more context(s)");for(var Q in A)A.hasOwnProperty(Q)&&h.Debug.trace('LOADER:  triggers have set contextTriggerMap "'+Q+'":"'+A[Q]+'"')}var N=function(a){return"undefined"!==
typeof A&&"undefined"!==typeof k[a].configName&&"undefined"!==typeof A[a]&&A[a]===k[a].configName?(h.Debug.trace('LOADER:  context "'+k[a].configName+'" triggered for '+a),!0):"undefined"===typeof A||"undefined"===typeof A[a]?(h.Debug.trace("LOADER:  published context triggered for "+a),!0):!1},J=function(a){h.Debug.error("Loader Error: "+a,"016")};h.Debug.info("LOADER:  Version "+[u.major,u.minor,u.inc].join("."));this.addEventHandler(this.Event.PREINIT,function(){var a="unknown";try{for(a in k){var b;
if(b=k.hasOwnProperty(a)){var c=a;b=ORA.hasVal(k[c].plugin)&&ORA.hasVal(k[c].plugin[ORA.Event.PREINIT])}b&&N(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preinit phase start',h.Debug.trace(c),k[a].plugin[ORA.Event.PREINIT](),c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preinit phase complete',h.Debug.trace(c))}}catch(e){ORA.abortModuleHelper(a,e)}},function(){J("preinit fail")});this.addEventHandler(this.Event.INIT,
function(){var a="unknown";try{for(a in k){var b;if(b=k.hasOwnProperty(a)){var c=a;b=ORA.hasVal(k[c].plugin)&&ORA.hasVal(k[c].plugin[ORA.Event.INIT])}b&&N(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _init phase start',h.Debug.trace(c),k[a].plugin[ORA.Event.INIT](),c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _init phase complete',h.Debug.trace(c))}}catch(e){ORA.abortModuleHelper(a,e)}},
function(){J("init fail")});this.addEventHandler(this.Event.PRELOAD,function(){var a="unknown";try{for(a in k){var b;if(b=k.hasOwnProperty(a)){var c=a;b=ORA.hasVal(k[c].plugin)&&ORA.hasVal(k[c].plugin[ORA.Event.PRELOAD])&&ORA.hasVal(k[c].plugin.oraConfigObj)&&!0===k[c].plugin.oraConfigObj.doLoad}b&&N(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preload phase start',h.Debug.trace(c),k[a].plugin[ORA.Event.PRELOAD](),
c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preload phase complete',h.Debug.trace(c))}}catch(e){ORA.abortModuleHelper(a,e)}},function(){J("preload fail")});this.addEventHandler(this.Event.LOAD,function(){var a="unknown";try{var b=function(f){return function(){ORA.Debug.debug(f+" downloaded successfully")}},c=function(f){f+="Module";return ORA[f]&&ORA[f].prototype.oraConfigObj&&ORA[f].prototype.oraConfigObj.loadPriority?ORA[f].prototype.oraConfigObj.loadPriority:0},e=function(f){var g;
if(g=k.hasOwnProperty(f))g=ORA.hasVal(k[f].plugin)&&ORA.hasVal(k[f].plugin[ORA.Event.LOAD])&&ORA.hasVal(k[f].plugin.oraConfigObj)&&!0===k[f].plugin.oraConfigObj.doLoad;g&&N(f)&&ORA.getExecuteState(f)!==ORA.Event.LOADER_MODULE_ABORT&&(ORA.setExecuteState(f,y.DOWNLOADING),g='LOADER:  product "'+f+'" with context name "'+(k[f].configName+'" _load phase start'),h.Debug.trace(g),k[f].plugin[ORA.Event.LOAD](b(f)),g='LOADER:  product "'+f+'" with context name "'+(k[f].configName+'" _load phase complete'),
h.Debug.trace(g))};for(a in k)k.hasOwnProperty(a)&&c(a)&&e(a);for(a in k)k.hasOwnProperty(a)&&!c(a)&&e(a)}catch(f){ORA.abortModuleHelper(a,f)}},function(){J("load fail")});this.addEventHandler(this.Event.LOADER_ABORT,function(){var a="unknown";C=!0;h.Debug.error("Loader global abort event","017");try{for(a in k)k.hasOwnProperty(a)&&ORA.hasVal(k[a].plugin)&&!0===k[a].plugin.oraConfigObj.doLoad&&(ORA.fireEvent(new ORA.Event(a+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS),!1,!0),ORA.setExecuteState(a,
ORA.Event.LOADER_MODULE_ABORT),ORA.clearTimer(a),ORA.Debug.error("Aborting product: "+a,"018"))}catch(b){ORA.abortModuleHelper(a,b)}},function(){J("abort fail")});var W=[];this.start=function(){var a=function(){h.fireEvent(new ORA.Event(ORA.Event.PREINIT,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.INIT,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.PRELOAD,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.LOAD,ORA.Event.STATUS_SUCCESS));h.Debug.debug("LOADER:  Synchronous functionality has finished firing")},
b=function(){for(var c in A)if(A.hasOwnProperty(c)){var e=h.getContextUrl(c,A[c]);"undefined"!==typeof e&&(h.Debug.debug("LOADER:  adding "+e+" to download"),W.push(e))}};try{ha(),ORA.hasVal(A)?(h.Debug.debug("LOADER:  contextTriggerMap contains contexts"),b(),h.downloadLibs("head",a,0,!0,W)):a()}catch(c){h.fireEvent(new ORA.Event(ORA.Event.LOADER_ABORT,ORA.Event.STATUS_SUCCESS))}};this.productReady=function(a,b,c){var e=k[a];c=c||"_product_ready";if(!e||e.executeState!==y.READY&&e.executeState!==
y.RUNNING)e?(ORA.addEventHandler(a+c,b),ORA.Debug.debug("attached lister for "+a+" "+c)):(ORA.Debug.debug("product was not found attaching to "+a+" "+c),ORA.addEventHandler(a+c,b));else try{b()}catch(f){ORA.Debug.debug("User supplied product ready callback failed "+f.message)}};this.productReady.push=function(a){ORA.productReady.apply(this,a);ORA.Debug.debug("productReady pushing function for "+a[0],"LOADER")};h.Debug.debug("ORA object created","LOADER");h.Debug.info('To dump config params use: "ORA.Debug.dumpParams()"');
h.Debug.info('To check the mode use: "ORA.Debug.checkMode(false)" - Use true if you wish to reset the mode.')}var p=function(v){var q=[];try{for(;0<v.length;)q=v.shift(),ORA.Debug.debug("productReady queue found when loading for "+q[0],"LOADER"),ORA.productReady.apply(this,q)}catch(u){ORA.Debug.debug("Error processing ORA.productReady queue "+u.message,"LOADER")}};if("undefined"===typeof ORA||"undefined"!==typeof ORA&&!ORA.ready){var r=[];"undefined"!==typeof ORA&&ORA.productReady&&(r=ORA.productReady);
ORA=new l(window,window.document,window.navigator,window.location);p(r);ORA.ready=!0}else console.error("ORA global namespace already in use, Infinity not loaded/setup")})();
(function(){"undefined"!==typeof ORA&&!0===ORA.ready&&(!0===ORA.isInitCompleted?ORA.Debug.error("The tag is being loaded multiple times. Exiting second tag initialization request."):(ORA.isInitCompleted=!0,ORA.registerPlugin=ORA.registerPlugin,ORA.abortModuleHelper=ORA.abortModuleHelper,ORA.setLoaderConversionTimeoutDefault=ORA.setLoaderConversionTimeoutDefault,ORA.loaderConversionTimeoutDefault=ORA.loaderConversionTimeoutDefault,ORA.downloadLib=ORA.downloadLib,ORA.reset=ORA.reset,ORA.productLoadInit=
function(){ORA.analyticsModule=function(){};ORA.analyticsModule.prototype.oraConfigObj={s_disableSeed:!1,alwaysLoad:!0,"ora-plugins":{cg:{enable:!0,cgDefs:"wt.cg_l1 wt.cg_l2 wt.cg_l3 wt.cg_l4 wt.cg_l5 wt.cg_l6 wt.cg_l7 wt.cg_l8 wt.cg_l9 wt.cg_l10".split(" "),blockCollect:!0},html5Video:{enable:!0,poll:!1,pctInc:25,beraconType:"auto",seek:!0,pollRate:250,nameCallback:null,beaconCurve:{300:30,60:10,600:60,130:30,420:45,1800:150},pause:!0,load:!1,cued:!1,loadMeta:!1,screenMode:!1,beacon:!0,postMessage:!1,
fixed:!1,quartile:!0,buffering:!1,bins:15,beaconRate:60,metaTags:!0,volume:!1},evtTrack:{enable:!0,eventList:{myClick:{eventTrigger:"mousedown",selector:"BUTTON.btnTest",eventCallback:'var el \x3d e["element"] || e["srcElement"] || {},payload \x3d {};payload["WT.ti"] \x3d "Button:" + el.textContent || el.innerText;payload["WT.dl"] \x3d "99";return {"data": payload};'}},trackSocial:!0,standardEvents:{anchor:!0,onsite:!0,offsite:!0,rightclick:!0,download:!0,javascript:!1,scrollTracking:!0},downloadtypes:"xls,doc,pdf,txt,csv,zip,docx,xlsx,rar,gzip,pptx",
socialTypes:{Reddit:["Reddit.com"],Pinterest:["Pinterest.com"],YouTube:["youtube.com"],Meetup:["Meetup.com"],"Google+":["plus.google.com"],VK:["VK.com"],Twitter:["Twitter.com"],Odnoklassniki:["Odnoklassniki.ru"],Weibo:["Weibo.com"],Facebook:["www.facebook.com"],"Ask.fm":["Ask.fm"],Tumblr:["Tumblr.com"],LinkedIn:["LinkedIn.com"],Instagram:["instagram.com"],Flickr:["Flickr.com"],Qzone:["Qzone.qq.com"]}},yt:{enable:!0,legacy:!1,pctInc:25,seek:!0,pause:!0,load:!1,cued:!1,loadMeta:!1,beacon:!0,mode:"auto",
quartile:!0,buffering:!1,loadAPI:!1,bins:15,beaconRate:60,volume:!1},fragment:{virtualPageView:!1,prefix:"anchor",blockCollect:!0,virtialDl:26,paramHandeling:"addPrefix",addAnchorName:"name",applyClickEventOnly:!1},bc:{enable:!0,poll:!1,pctInc:25,beraconType:"auto",seek:!0,pollRate:250,nameCallback:null,beaconCurve:{300:30,60:10,600:60,130:30,420:45,1800:150},pause:!0,load:!1,cued:!1,preProcess:null,loadMeta:!1,screenMode:!1,beacon:!0,maxBinds:10,postMessage:!1,fixed:!1,playerId:"div[id^\x3d'vjs_video']:not([id$\x3d'_api']):not([id*\x3d'_component'])",
quartile:!0,buffering:!1,bins:15,beaconRate:60,metaTags:!0,volume:!1},heatmap:{enable:!0,maxymiserEnable:!1,blockCollect:!0},cookieCutter:{readCookies:[{cookie:{TEST:"ora.cook_a"},options:{persist:!0}},{cookie:{ORA_FPC:{id:"ora.c_id",ss:"ora.c_ss",lv:"ora.c_lv"}},options:{parseOn:":",parseLv:"\x3d"}},{cookie:{ELOQUA:{GUID:"ora.eloqua"}}},{cookie:{utag_main:{_ss:"ora.u_ss",_st:"ora.u_st",v_id:"ora.u_vid",_sn:"ora.u_sn",ses_id:"ora.u_ses_id"}},options:{parseOn:"$",parseLv:":",persist:!1}}],enable:!0},
pp:{enable:!0,cookieDays:365,priority:100,defPrefix:"DCSext",params:["wt.gcm_uid","wt.p_cookie_att","wt.gcm_uid","wt.p_status","vtid"],useMostRecent:!0,cookieName:"WTPERSIST"},plt:{enable:!0,waitTime:150,sampleRate:50,assetFilter:".*js",maxT:2,enablePerf:!1,perfLimit:50}},timezone:0,enabled:!0,DNTBehavior:"honorDNT",skip_qp_no_equals:!0,s_dependencies:"common:running","hosted-plugins":{InfinityPlugin:{enable:!0,src:"https://www.oracle.com/asset/web/analytics/infinity_common.js",blockCollect:!1}},
defaultCollectionServer:"dc.oracleinfinity.io",s_useTrackingPipeline:!0,libUrl:"//c.oracleinfinity.io/acs/account/wh3g12c3gg/js/oracledocs/analytics-development/analytics.js",accountGuid:"wh3g12c3gg",tagId:"oracledocs",secureCookie:!1,FPCConfig:{domain:".oracle.com",sessionOnly:!1,autoTLD:!1},cookieTypes:"firstpartyonly",destinations:[{accountGuid:"wh3g12c3gg"}],s_TrackingPipelineTimeout:4E3};typeof ORA.analyticsModule.prototype.oraConfigObj.enabled&&!1===ORA.analyticsModule.prototype.oraConfigObj.enabled?
ORA.Debug.debug("analytics  module disabled - exiting module setup"):(ORA.analyticsModule.prototype.preinit=function(){try{ORA.Debug.debug("PREINIT: Executing Preinit script")}catch(l){ORA.abortModuleHelper("analytics",l)}},ORA.analyticsModule.prototype.init=function(){try{this.oraConfigObj.key="value",void 0===this.oraConfigObj.doLoad&&(this.oraConfigObj.doLoad=!0),this.oraConfigObj.doLoad=this.oraConfigObj.doLoad||this.oraConfigObj.alwaysLoad}catch(l){ORA.abortModuleHelper("analytics",l)}},ORA.analyticsModule.prototype.preload=
function(){try{var l=0;ORA.analyticsModule.prototype.oraConfigObj.s_conversionTimeout&&(l=ORA.analyticsModule.prototype.oraConfigObj.s_conversionTimeout);ORA.setLoaderConversionTimeoutDefault(Math.max(l,ORA.loaderConversionTimeoutDefault()));ORA.Debug.debug("PRELOAD:  Executing preload script")}catch(p){ORA.abortModuleHelper("analytics",p)}},ORA.analyticsModule.prototype.load=function(l){try{ORA.Debug.debug("LOAD:  Executing load phase"),ORA.downloadLib("head",l,function(){ORA.fireEvent(new ORA.Event("analytics_"+
ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},0,!0,this.oraConfigObj.libUrl)}catch(p){ORA.abortModuleHelper("analytics",p)}},ORA.analyticsModule.prototype.postload=function(){ORA.Debug.debug("POSTLOAD:  Executing postload analytics complete");try{ORA.Debug.info("LOADER:  ORA.analyticsModule.prototype: postload"),ORA.analytics.setup(ORA.analyticsModule.prototype.oraConfigObj)}catch(l){ORA.abortModuleHelper("analytics",l)}},ORA.analyticsModule.prototype.abort=function(){try{ORA.Debug.debug("ABORT:  Executing analyticsModule abort")}catch(l){ORA.abortModuleHelper("analytics",
l)}});ORA.analyticsModule.ProductName="analytics";ORA.registerPlugin(ORA.analyticsModule,"development")},function(){var l=!0;ORA.sizzleModule=function(){};ORA.sizzleModule.prototype.oraConfigObj={libUrl:"//c.oracleinfinity.io/acs/common/js/lib/sizzle.min.js",doLoad:!0,s_dependencies:""};ORA.sizzleModule.setLoaded=function(p){l=p};ORA.sizzleModule.getLoaded=function(){return l};ORA.sizzleModule.prototype.load=function(p){try{ORA.updateDependencies("sizzle",this.oraConfigObj.s_dependencies),"undefined"===
typeof JSON&&ORA.isDependency("sizzle")?(ORA.Debug.debug("Sizzle not detected"),ORA.sizzleModule.setLoaded(!1),ORA.downloadLib("head",p,function(){ORA.abortModuleHelper("sizzle","failed to download sizzle")},0,!0,this.oraConfigObj.libUrl)):(ORA.sizzleModule.setLoaded(!0),ORA.setExecuteState("sizzle","ready"))}catch(r){ORA.abortModuleHelper("sizzle",r)}};ORA.sizzleModule.prototype.postload=function(){};ORA.sizzleModule.ProductName="sizzle";ORA.registerPlugin(ORA.sizzleModule,"default")}(),function(){var l=
!0;ORA.jsonModule=function(){};ORA.jsonModule.prototype.oraConfigObj={libUrl:"//c.oracleinfinity.io/acs/common/js/lib/json2.js",doLoad:!0,s_dependencies:""};ORA.jsonModule.setLoaded=function(p){l=p};ORA.jsonModule.getLoaded=function(){return l};ORA.jsonModule.prototype.load=function(p){try{ORA.updateDependencies("json",this.oraConfigObj.s_dependencies),"undefined"===typeof JSON&&ORA.isDependency("json")?(ORA.Debug.debug("JSON not detected"),ORA.jsonModule.setLoaded(!1),ORA.downloadLib("head",p,function(){ORA.abortModuleHelper("json",
"failed to download json");ORA.abortModuleHelper("analytics","failed to download json")},0,!0,this.oraConfigObj.libUrl)):(ORA.jsonModule.setLoaded(!0),ORA.setExecuteState("json","ready"))}catch(r){ORA.abortModuleHelper("analytics",r)}};ORA.jsonModule.prototype.postload=function(){};ORA.jsonModule.ProductName="json";ORA.registerPlugin(ORA.jsonModule,"default")}(),function(){ORA.Event.BLUEKAI_DATA_READY="bluekai_data_ready";var l={},p=function(){};"undefined"===typeof Array.isArray&&(Array.isArray=
function(h){return"[object Array]"===Object.prototype.toString.call(h)});var r=function(h,C){var B=C||"",x;for(x in h)h.hasOwnProperty(x)&&(Array.isArray(h[x])?l["ora."+B+"_"+x]=h[x].join(";"):"object"===typeof h[x]?r(h[x],B+"_"+x):l["ora."+B+"_"+x]=h[x]);return null},v=function(h){var C=[],B;for(B in h)h.hasOwnProperty(B)&&(C.push(String(B)),C.push(encodeURIComponent(h[B])));return C.join(",")},q=function(h){h&&h.data&&"bluekai"===h.data.source&&(r(h.data,"odc"),"undefined"!==typeof ORA.setCookie?
ORA.setCookie("bluekai_uid_plugin",v(l),"; path\x3d/"):document.cookie="bluekai_uid_plugin\x3d"+v(l)+"; path\x3d/");p()},u=function(){window.addEventListener?window.addEventListener("message",q,!1):ORA.Debug.debug("bluekai reguires addEventListener support","LOADER-bluekai")};p=function(){ORA.Debug.debug("Removing postMessage lister for bluekai data","ANA-bluekai_uid_plugin");window.removeEventListener?window.removeEventListener("message",q):window.removeEvent?window.removeEvent("onmessage",q):ORA.Debug.debug("Browser does not support Removing messageListeners - exiting",
"ANA-bluekai_uid_plugin");ORA.fireEvent(new ORA.Event(ORA.Event.BLUEKAI_DATA_READY,ORA.Event.STATUS_SUCCESS))};ORA&&ORA.fireEvent&&ORA.Debug&&setTimeout(u,1);window.ORA.bkLoader=u}(),function(){ORA.commonModule=function(){};ORA.Event.COMMON_LOAD_COMPLETE="common_load_complete";ORA.Event.COMMON_ORA_PLUGINMGR_READY="common_ora_pluginmgr_ready";ORA.Event.COMMON_HOSTED_PLUGINMGR_READY="common_hosted_pluginmgr_ready";ORA.Event.COMMON_TRACKING_FLUSH="common_tracking_flush";ORA.Event.COMMON_COM_EXEC_REQ=
"common_com_exec_req";ORA.Event.COMMON_BEFORE_GETID="common_before_getid";ORA.Event.COMMON_GETID="common_get_id";ORA.Event.COMMON_PRODUCT_READY="common_product_ready";ORA.commonModule.prototype.oraConfigObj={libUrl:"//c.oracleinfinity.io/acs/common/js/1.3.43/common.js",doLoad:!0,s_dependencies:"json:running"};ORA.commonModule.prototype.load=function(l){try{(!ORA.hasVal(ORA.common)||ORA.hasVal(ORA.common)&&!ORA.hasVal(ORA.common.TrackingPipeline))&&ORA.isDependency("common")&&ORA.downloadLib("head",
l,function(){ORA.fireEvent(new ORA.Event("common"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},0,!0,this.oraConfigObj.libUrl)}catch(p){ORA.abortModuleHelper("common",p)}};ORA.commonModule.prototype.postload=function(){ORA.common.setup()};ORA.commonModule.ProductName="common";ORA.registerPlugin(ORA.commonModule,"default")}(),function(){ORA.Event.ANA_LOAD_COMPLETE="analytics_load_complete";ORA.Event.ANA_ORA_PLUGINS_LOADED="analytics_ora_plugins_loaded";ORA.Event.ANA_HOSTED_PLUGINS_LOADED=
"analytics_hosted_plugins_loaded";ORA.Event.ANA_ORA_PLUGINS_INIT="analytics_ora_plugins_init";ORA.Event.ANA_HOSTED_PLUGINS_INIT="analytics_hosted_plugins_init";ORA.Event.ANA_DCS_SETUP="analytics_dcs_setup";ORA.Event.ANA_PRODUCT_READY="analytics_product_ready";ORA.Event.ANA_SETUP_COMPLETE="analytics_setup_complete";ORA.Event.ANA_BEFORE_PAGE_ANALYSIS="analytics_before_page_analysis";ORA.Event.ANA_AFTER_PAGE_ANALYSIS="analytics_after_page_analysis";ORA.Event.ANA_BEFORE_GETID="analytics_before_getid";
ORA.Event.ANA_AFTER_GETID="analytics_after_getid";ORA.Event.ANA_PV_MUTATE="analytics_pv_mutate";ORA.Event.ANA_DATA_SEND="analytics_data_send";ORA.Event.LOADER_CLICK="loader_click";ORA.Event.LOADER_PRE_EXECUTE="loader_pre_execute";ORA.Event.LOADER_EXECUTE="loader_execute";ORA.Event.LOADER_RESET="loader_reset";ORA.Event.LOADER_COLLECT="loader_collect";ORA.Event.LOADER_VIEW="loader_view";ORA.getContextName=function(){return ORA.getProduct("analytics")&&ORA.getProduct("analytics").configName||""};ORA.getConfigName=
function(){return ORA.getProduct("analytics")&&ORA.getProduct("analytics").configName||""};var l=function(p,r){ORA.fireEvent(new ORA.Event(p,ORA.Event.STATUS_SUCCESS,null,r),null,null,!0)};ORA.collect=function(p){l(ORA.Event.LOADER_COLLECT,p);return!0};ORA.view=function(p){l(ORA.Event.LOADER_VIEW,p);return!0};ORA.click=ORA.sendEvent=function(p){l(ORA.Event.LOADER_CLICK,p);return!0};ORA.regPlugin=function(p,r,v){var q=function(){ORA.Debug.debug("regPlugin - call of deferred register of "+p,"LOADER");
void 0===ORA.analytics.plugins[p]?(ORA.Debug.debug("Registering init for "+p),ORA.common.pluginMgr._regPlugin(p,r,v)):ORA.analytics.plugins[p]&&ORA.analytics.plugins[p].src?(ORA.analytics.plugins[p].loaded=!0,ORA.common.hostedPluginMgr._regPlugin(p,r,v,"hosted-plugins")):ORA.common.pluginMgr._regPlugin(p,r,v)};ORA.common&&ORA.common.pluginMgr&&ORA.common.pluginMgr.isReady&&!0===ORA.common.pluginMgr.isReady()?(ORA.Debug.debug("ORA.common.pluginMgr exists so register is possible"),q()):(ORA.Debug.debug("regPlugin - deferred register of "+
p,"LOADER"),ORA.analytics.plugins[p]&&ORA.analytics.plugins[p].src?ORA.addEventHandler(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,q,null,!0):ORA.addEventHandler(ORA.Event.COMMON_ORA_PLUGINMGR_READY,q,null,!0))}}(),function(){ORA.responsysModule=function(){};ORA.responsysModule.prototype.oraConfigObj={doLoad:!0,s_dependencies:"",config:{cookie_name:"responsys_cookie_default",fallback_cookie_domain_level:0,fallback_timeout:"2000",urlSuffix:"/pub/cc",responsysURL:"",additionalParms:"_pb_\x3dR\x26_tt_\x3dQ"}};
ORA.responsysModule.prototype.moveAndToResp=function(l,p){for(var r in l.config)l.config.hasOwnProperty(r)&&""!==l.config[r]&&(p.config[r]=l.config[r])};ORA.responsysModule.prototype.validateSettings=function(l){l.config.responsysURL||(ORA.debug("missing required setting for responsysURL, disabling module","responsys"),l.enabled=!1)};ORA.responsysModule.prototype.postload=function(){var l=function(){ORA.Debug.debug("responsysModule load pixel failed - fallback to standard cookie",ORA.responsysModule.ProductName);
ORA.responsysModule.prototype.cookieFallback()},p=function(){ORA.Debug.debug("responsysModule load pixel success",ORA.responsysModule.ProductName)};try{if(this.responsysExists()){var r=this.prepareUrl()+this.removeParameterList(location.search,this.oraConfigObj.config.additionalParms);r+="\x26"+this.oraConfigObj.config.additionalParms+location.hash;this.responsysLoadPixel(r,p,l,this.oraConfigObj.config.fallback_timeout);return!0}ORA.setExecuteState("responsysModule","ready")}catch(v){return ORA.Debug.debug("responsysModule load error "+
v.message),!1}};ORA.responsysModule.prototype.load=function(){try{var l={};if(ORA.analyticsModule&&ORA.analyticsModule.prototype&&ORA.analyticsModule.prototype.oraConfigObj&&ORA.analyticsModule.prototype.oraConfigObj.responsys){var p=ORA.responsysModule.prototype.oraConfigObj;l=ORA.analyticsModule.prototype.oraConfigObj.responsys;l.doLoad&&(p.doLoad=l.doLoad);l.s_dependencies&&(p.s_dependencies=l.s_dependencies);ORA.responsysModule.prototype.moveAndToResp(l,p);ORA.responsysModule.prototype.validateSettings(l)}void 0!==
l.enabled&&l.enabled?(ORA.updateDependencies("responsysModule","analytics:downloading"),ORA.setExecuteState("responsysModule","ready")):ORA.debug("responsys module not enabled","responsys")}catch(r){ORA.Debug.debug("responsysModule load error "+r.message)}};ORA.responsysModule.prototype.responsysExists=function(l){l=ORA.parseQueryString(l);return!!(l&&l._ri_&&l._ei_)};ORA.responsysModule.prototype.responsysLoadPixel=function(l,p,r,v){var q=new Image,u=!1;q.onload=function(){u||(u=!0,p(),ORA.Debug.debug("Responsys pixel loaded",
ORA.responsysModule.ProductName))};q.onerror=function(){u||(u=!0,r(),ORA.Debug.debug("Responsys pixel load failed",ORA.responsysModule.ProductName))};window.setTimeout(function(){u&&1!==v||(u=!0,ORA.Debug.debug("Responsys pixel load failed",ORA.responsysModule.ProductName),r())},v);q.src=l};ORA.responsysModule.prototype.cookieFallback=function(l){var p=ORA.parseQueryString(l),r=this.oraConfigObj.config;l=r.cookie_name;p="_ri_"+p._ri_+"\x26_ei_"+p._ei_;var v=location.hostname.split(".");r=r.fallback_cookie_domain_level;
var q=new Date,u="";for(q.setTime(q.getTime()+63113851500);r;)v.shift(),r--;v.join(".")!==location.host&&(u=";domain\x3d"+v.join("."));v="; path\x3d/ ; expires\x3d "+q.toGMTString()+u;ORA.Debug.debug("Setting fallback cookie","responsysModule");ORA.setCookie(l,p,v)};ORA.responsysModule.prototype.removeParameter=function(l,p){var r=l.split("?");if(2<=r.length){for(var v=encodeURIComponent(p)+"\x3d",q=r[1].split(/[&;]/g),u=q.length;0<u;)u--,-1!==q[u].lastIndexOf(v,0)&&q.splice(u,1);return 0<q.length?
r[0]+q.join("\x26"):r[0]}return l};ORA.responsysModule.prototype.removeParameterList=function(l,p){for(var r=l,v=p.split("\x26"),q=0;q<v.length;q++){var u=v[q].split("\x3d");r=this.removeParameter(r,u[0])}return"?"+r};ORA.responsysModule.prototype.prepareUrl=function(){var l=this.oraConfigObj.config,p=l.responsysURL;l.urlBase&&""!==l.urlBase&&(p=l.urlBase);return p+l.urlSuffix};ORA.responsysModule.ProductName="responsysModule";ORA.registerPlugin(ORA.responsysModule,"default")}(),ORA.productLoadInit(),
ORA.start()))})();